[project]
name = "streamlit-income-share"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "altair>=5.4.1",
    "pandas>=2.2.3",
    "streamlit>=1.40.1",
]
