---
title: "Connect Widgets - Palmer Penguins"
output: html_document
resource_files:
  - imgs/penguins.png
---

```{r setup, include=FALSE}
library(connectwidgets)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

client <- connect(
  server  = "https://colorado.posit.co/rsc/",
  api_key = Sys.getenv("CONNECT_API_KEY")
)
```

A curated list of Posit Connect demos using the [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/) data set ðŸ§.


## Applications

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("Application") |> 
  rsc_grid()
```

## APIs

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("API") |> 
  rsc_grid()
```

## Documents

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("Document") |> 
  rsc_grid()
```

## Pins

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("Pins") |> 
  rsc_grid()
```

## R Content

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("R") |> 
  rsc_grid()
```

## Python content

```{r}
client |> 
  content() |> 
  by_tags("Demo: Palmer Penguins") |> 
  by_tags("Python") |> 
  rsc_grid()
```
