[project]
name = "fastapi-stock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "datetime>=5.5",
    "fastapi>=0.115.5",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "pydantic>=2.9.2",
    "uvicorn>=0.32.0",
]
