name: build-env-and-test-publish
run-name: ${{ github.actor }} is using GitHub Actions for testing and publishing to Connect
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
  push:
    branches: [master, main, la-cicd-test]
  pull_request:
    branches: [master, main, la-cicd-test]
    
jobs:
  test-connectwidgets-penguins:
    name: test-connectwidgets-penguins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.1
          py-version: 3.10.12
          use-public-rspm: true
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install setup-connect
        uses: rstudio/actions/setup-connect@main
      - name: Setup renv environment
        uses: r-lib/actions/setup-renv@v2
        with: 
          working-directory: ./R/connectwidgets-penguins/:connectwidgets-penguins
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rsconnect 
            any::dplyr
      - name: Install rsconnect package
        run: Rscript --vanilla -e "install.packages('rsconnect', repos=c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/noble/latest'))"
      - name: Version rsconnect package
        run: Rscript --vanilla -e "packageVersion('rsconnect')"
      - name: Update lock file 
        run: Rscript --vanilla -e "renv::snapshot()"
      #- name: Create manifest.json
      #  shell: Rscript {0}
      #  run: |
      #    rsconnect::writeManifest()
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: all
          show-logs: TRUE
          force: FALSE
          dir: ./R/connectwidgets-penguins/report/:connectwidgets-penguins/report
      - name: Use Connect API to set content title and assign tag
        run: |
          export DATA='{"title": "Using connectwidgets with Posit Connect"}'
          export CONTENT_NAME='connectwidgets-penguins'
          export contentguid=$(curl -H "Authorization: KEY ${{ secrets.CONNECT_API_KEY }}" ${{ secrets.CONNECT_URL }}/__api__/v1/content?name=${CONTENT_NAME} | jq -r '.[].guid')
          echo contentguid
          curl --silent --show-error -L --max-redirs 0 --fail -X PATCH -H "Authorization: Key ${{ secrets.CONNECT_API_KEY }}" --data "${DATA}" "${{ secrets.CONNECT_URL }}__api__/v1/content/${contentguid}"
          export DATA2='{"tag_name": "posit-demo-assets"}'
          curl --silent --show-error -L --max-redirs 0 --fail -X POST -H "Authorization: Key ${CONNECT_API_KEY}" "${CONNECT_URL}__api__/v1/tags" --data "${DATA2}" "${CONNECT_URL}__api__/v1/tags"
          export tag_id=$(curl -H "Authorization: KEY ${{ secrets.CONNECT_API_KEY }}" ${{ secrets.CONNECT_URL }}/__api__/v1/tags/${contentguid} | jq -r '.[].id')
          echo tag_id
          curl --silent --show-error -L --max-redirs 0 --fail -X PATCH -H "Authorization: Key ${{ secrets.CONNECT_API_KEY }}" --data "${tag_id}" "${{ secrets.CONNECT_URL }}__api__/v1/content/${contentguid}/tags"
          
    