on:
    workflow_dispatch:
    pull_request:
        branches:
            - main 

jobs:
    list-manifests:
        runs-on: ubuntu-latest
        outputs:
            manifests: ${{ steps.list-manifests.outputs.manifests }}
        steps:
            - name: List manifests
              id: list-manifests
              uses: mirko-felice/list-files-action@v3.0.5
              with:
                repo: ${{ github.repository }}
                ref: ${{ github.ref }}
                path: "."
                ext: ".json"

    deploy:
        needs: list-manifests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                paths: ${{ fromJson(needs.list-manifests.outputs.manifests) }}
        steps:
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
                cache: "pip"
            - name: Install CLI
              run: python -m pip install rsconnect-python
            - name: Deploy
              run: |
                echo ${{ matrix.paths }}
