name: connect-publish
run-name: ${{ github.actor }} is using GitHub Actions for publishing to Connect
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
  push:
    branches: [master, main, la-cicd-test]
  pull_request:
    branches: [master, main, la-cicd-test]
    
jobs:
  pub-connectwidgets-penguins:
    name: pub-connectwidgets-penguins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.1
          py-version: 3.10.12
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: all
          show-logs: TRUE
          force: FALSE
          dir: ./R/connectwidgets-penguins/report/:connectwidgets-penguins/report
      - name: Use Connect API to set content title
        run: |
          export DATA='{"title": "Using connectwidgets with Posit Connect"}'
          export CONTENT_NAME='A curated list of Posit Connect demos using the Palmer Penguins data set'
          export contentguid=$(curl -H "Authorization: KEY ${{ secrets.CONNECT_API_KEY }}" ${{ secrets.CONNECT_URL }}/__api__/v1/content?name=${CONTENT_NAME} | jq -r '.[].guid')
          echo contentguid
          curl --silent --show-error -L --max-redirs 0 --fail -X PATCH -H "Authorization: Key ${{ secrets.CONNECT_API_KEY }}" --data "${DATA}" "${{ secrets.CONNECT_SERVER }}__api__/v1/content/${contentguid}"
    
    
    